### ISSUE TITLE
Tensorflow version, learning part not working

### ISSUE THREAD

**Issue by B-Seif** [ykotseruba/PedestrianActionBenchmark#27]
First of all, I would like to congratulate you on this great work. I try to reproduce the results and see how to integrate a new approach into this benchmark. However, not having experience with Tensorflow, I'm having a little trouble debugging the error below.
In fact, I have a problem with Tensorflow learning part of the code.  The generation of feautre is going well but the learning part is not working.  Below is what I get as an error. I followed all the steps you recommended. I'm using Docker and I have version 2.16 of Tensorflow.

Thanks for your help.

```
python train_test.py -c config_files/PCPA.yaml 
```

```
 Total params: 31,165,953 (118.89 MB)
 Trainable params: 31,165,953 (118.89 MB)
 Non-trainable params: 0 (0.00 B)
### Class weights: negative 0.204 and positive 0.796 ###
lerreur commence par là je crois 
Traceback (most recent call last):
  File "/data/PedestrianActionBenchmark/PedestrianActionBenchmark/train_test.py", line 165, in <module>
    run(config_file=config_file)
  File "/data/PedestrianActionBenchmark/PedestrianActionBenchmark/train_test.py", line 107, in run
    saved_files_path = method_class.train(beh_seq_train, beh_seq_val, **configs['train_opts'],
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/PedestrianActionBenchmark/PedestrianActionBenchmark/action_predict.py", line 759, in train
    history = train_model.fit(x=data_train['data'][0],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/keras/src/utils/traceback_utils.py", line 123, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.11/dist-packages/tensorflow/python/data/ops/from_generator_op.py", line 124, in _from_generator
    raise TypeError(f"`output_signature` must contain objects that are "
TypeError: `output_signature` must contain objects that are subclass of `tf.TypeSpec` but found <class 'list'> which is not.
```

**Comment by ykotseruba** [comment]
Hi, thank you for your interest in our work and for notifying us of this problem.
This issue is caused by the generator in the recent versions of tensorflow. Changing line 2379 in action_predict.py to `return tuple(X)` fixes it.

**Comment by ykotseruba** [comment]
I'm rerunning some results on the newer version of TF, if they are ok, I'll update the repo.

**Comment by B-Seif** [comment]
Hi, Thanks for your help. 
Could you tell me how to change please? 
```python  else:
            _data_rgb = (_data_samples[feature_type], _data_samples['crossing'])
            _data_opt_flow = (_data_samples['optical_flow'], _data_samples['crossing'])

        return {'data_rgb': _data_rgb,
                'ped_id': data['ped_id'],
                'tte': data['tte'],
                'data_opt_flow': _data_opt_flow,
                'data_params_rgb': {'data_types': [feature_type],
                                    'data_sizes': [data_type_sizes_dict[feature_type]]},
                'data_params_opt_flow': {'data_types': ['optical_flow'],
                                         'data_sizes': [data_type_sizes_dict['optical_flow']]},
                'effective_dimension': effective_dimension,
                'count': {'neg_count': neg_count, 'pos_count': pos_count}}
````
In the meantime, I disabled generation step (in config file I set generator= False) and it works. However, I can't reproduce the results as they are in the paper. 
Thanks again.

**Comment by 2tianyao1** [comment]
> 你好，谢谢你的帮助。 你能告诉我如何更改吗？
> 
>             _data_rgb = (_data_samples[feature_type], _data_samples['crossing'])
>             _data_opt_flow = (_data_samples['optical_flow'], _data_samples['crossing'])
> 
>         return {'data_rgb': _data_rgb,
>                 'ped_id': data['ped_id'],
>                 'tte': data['tte'],
>                 'data_opt_flow': _data_opt_flow,
>                 'data_params_rgb': {'data_types': [feature_type],
>                                     'data_sizes': [data_type_sizes_dict[feature_type]]},
>                 'data_params_opt_flow': {'data_types': ['optical_flow'],
>                                          'data_sizes': [data_type_sizes_dict['optical_flow']]},
>                 'effective_dimension': effective_dimension,
>                 'count': {'neg_count': neg_count, 'pos_count': pos_count}}
> 同时，我禁用了生成步骤（在配置文件中我设置了 generator=False），它仍然有效。但是，我无法重现论文中的结果。 再次感谢。

I have the same problem, can I ask if you solved it?
